live/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/apply', 'FrontController@applyNow');
Route::post('apply', 'FrontController@storeApplication');
Route::get('/chat', function () {
    return view('chat');
});
// Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');
    Route::get('logout', 'Auth\LoginController@logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['middleware'=>['auth']],function() {
    Route::get('/home', 'DashboardController@index');
    Route::resource('/home/applications', 'ApplicationController');
    Route::resource('/home/navigation', 'NavigationController');
    Route::resource('/home/advertisement', 'AdvertisementController');

});

live/app/Http/Controllers/demo.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Navigation;

class NavigationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $navigation_list=Navigation::all();
       return view('backend.navigation.table',compact('navigation_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parents_list=['No Parents'];
        $parents_list=array_merge($parents_list,Navigation::pluck('title','id')->toArray());
//        $parents_list
//        return ($parents_list);
        return view('backend.navigation.create',compact('parents_list'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required|unique:navigations',
            'url' => 'required',
        ]);
        $navigation=new Navigation();
        $navigation->title=$request->title;
        $navigation->parent_id=$request->parent_id;
        $navigation->url=$request->url;
        $navigation->status=($request->status)?1:0;
            $result=$navigation->save();
        if($result){
            session()->flash('message', 'Navigation Saved Succefully.');
            return redirect('home/navigation');
        }
        else{
            session()->flash('message', 'Something Went Wrong! Please Try Again.');
            return redirect()->back()->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $parents_list=['No Parents'];
        $parents_list=array_merge($parents_list,Navigation::where('id','!=',$id)->pluck('title','id')->toArray());
        $navigation=Navigation::find($id);
        return view('backend.navigation.edit',compact('parents_list','navigation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'url' => 'required',
        ]);
        $navigation=Navigation::find($id);
        $navigation->title=$request->title;
        $navigation->parent_id=$request->parent_id;
        $navigation->url=$request->url;
        $navigation->status=($request->status)?1:0;
        $result=$navigation->save();
        if($result){
            session()->flash('message', 'Navigation Updated Succefully.');
            return redirect('home/navigation');
        }
        else{
            session()->flash('message', 'Something Went Wrong! Please Try Again.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Navigation::find($id)->delete();
        session()->flash('message', 'Navigation Deleted Successfully.');
        return redirect('home/navigation');
    }
}

live/resources/views/backend/demo/create.blade.php
@extends('backend.header')
@section('content')
<div class="col-md-12">
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            {{--<ul>--}}
            {{--@foreach ($errors->all() as $error)--}}
            {{--<li>{{ $error }}</li>--}}
            {{--@endforeach--}}
            {{--</ul>--}}
        </div>
    @endif
    {{ Form::open(['url'=>'home/navigation', 'method'=>'POST', 'class' => 'common-form eq-half-form' ]) }}

        @include('backend.navigation.partial.form')
        <button type="submit" class="btn btn-info btn-fill">Submit
        </button>
        <div class="clearfix"></div>
    {!! Form::close() !!}
</div>
    @stop

live/resources/views/backend/demo/edit.blade.php
@extends('backend.header')
@section('content')
    <div class="col-md-12">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                {{--<ul>--}}
                {{--@foreach ($errors->all() as $error)--}}
                {{--<li>{{ $error }}</li>--}}
                {{--@endforeach--}}
                {{--</ul>--}}
            </div>
        @endif
            {!! Form::model($navigation, [
                    'route' => ['navigation.update', $navigation->id],
                    'class' => 'form-horizontal',
                    'method'=> 'PUT'
                ])
            !!}
        @include('backend.navigation.partial.form')
        <button type="submit" class="btn btn-info btn-fill">Update
        </button>
        <div class="clearfix"></div>
        {!! Form::close() !!}
    </div>
@stop

live/resources/views/backend/demo/table.blade.php
@extends('backend.header')
@section('content')
    <section class="content-header">
        <h1>
           <span>
        <a href="{{ url('home/navigation/create') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
                Add New
            </button>
        </a>
    </span>
        </h1>
    </section>
    @if(Session::has('message'))
        <div class="content_top">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ session('message') }}  <!-- equivalent to Session::get('flash_message') -->
            </div>
        </div>
    @endif
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>SN</th>
                <th>Title</th>
                <th>Parent</th>
                <th>Url</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                <?php
                $i=1;
                ?>
                @foreach($navigation_list as $navigation)
                    <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{$navigation->title}}</td>
                        <td>{{$navigation->parent_id}}</td>
                        <td>{{$navigation->url}}</td>
                        <td>{{$navigation->status}}</td>
                        <td>
                            <a type="button" type="button" class="btn btn-primary btn-sm"
                               href="{{ route('navigation.edit', array($navigation->id)) }}">
                                <i class="flaticon-edit"> Edit</i>
                            </a>
                            <form action="{{ route('navigation.destroy', array($navigation->id)) }}" method="POST" class="delete-user-form">
                                <input name="_method" value="DELETE" type="hidden">
                                {!! csrf_field() !!}

                                <button type="submit" class="btn btn-sm btn-danger"onclick="return confirm('Are you sure, you want to delete it?');">
                                    <i class="flaticon-delete-button">Delete</i>
                                </button>

                            </form>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </div>

@stop