live/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/apply', 'FrontController@applyNow');
Route::post('apply', 'FrontController@storeApplication');
Route::get('/chat', function () {
    return view('chat');
});
// Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');
    Route::get('logout', 'Auth\LoginController@logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['middleware'=>['auth']],function() {
    Route::get('/home', 'DashboardController@index');
    Route::resource('/home/applications', 'ApplicationController');
    Route::resource('/home/navigation', 'NavigationController');
    Route::resource('/home/advertisement', 'AdvertisementController');

});

live/app/Application.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    protected $fillable = [
        'full_name', 'address', 'country_id','email','contact_no','education_level_id','faculty','intrested_course_id','intrested_country_id','married_status',
        'ielts','tofel','sat','gre','other_test'
    ];
}

live/app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Application;

class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    	// die('herer');
        $application=Application::orderBy('id','DESC')->paginate(10);
        // dd($application);
        return view('backend.application.table',compact('application'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $application=Application::find($id);
       return view('backend.application.details',compact('application'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Application::find($id)->delete();
        session()->flash('message', 'Griffith service Deleted.');
        return redirect('home/applications');
    }
}

live/resources/views/backend/application/details.blade.php
@extends('backend.header')
@section('content')

<div class="box">
    <div class="box-body">
      <h1>
           <span>
        <a href="{{ url('home/applications') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
               <- Back
            </button>
        </a>
    </span>
        </h1>

    Name: <label>{{$application->full_name}}</label></br>
    Address: <label>{{$application->address}}</label></br>
    Emali: <label>{{$application->email}}</label></br>
    Contact No: <label>{{$application->contact_no}}</label></br>
    Faculty: <label>{{$application->faculty}}</label></br>
    Highest Education Level: <label>@if($application->education_level_id==1)
	                        {{'SLC'}}

	                        @elseif($application->education_level_id==2)
	                        {{'10+2'}}

	                        @elseif($application->education_level_id==3)
	                        {{'Bachelor'}}

	                        @elseif($application->education_level_id==4)
	                        {{'Master'}}

	                        @endif</label></br>
    Intrested Course: <label>@if($application->intrested_course_id==1)
	                        {{'Course 1'}}

	                        @elseif($application->intrested_course_id==2)
	                        {{'Course 2'}}

	                        @elseif($application->intrested_course_id==3)
	                        {{'Course 3'}}

	                        @elseif($application->intrested_course_id==4)
	                        {{'Course 4'}}

	                        @endif</label></br>
    Intrested Country: <label>@if($application->intrested_country_id==1)
	                        {{'Nepal'}}

	                        @elseif($application->intrested_country_id==2)
	                        {{'China'}}

	                        @elseif($application->intrested_country_id==3)
	                        {{'India'}}

	                        @elseif($application->intrested_country_id==4)
	                        {{'Bhutan'}}

	                        @endif
</label></br>
    Work Experience: <label>{{$application->work_experience}}</label></br>

    </div>

</div>

@stop

live/resources/views/backend/application/table.blade.php
@extends('backend.header')
@section('content')
 
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>SN</th>
                <th>Name</th>
                <th>Address</th>
                <th>Email</th>
                <th>Phone No</th>
                <th>Education Level</th>
                <th>Intrested Course</th>
                <th>Intrested Country</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $i=1;
            ?>
            @foreach($application as $app)
                <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $app->full_name }}</td>
                    <td>{{ $app->address }}</td>
                    <td>{{ $app->email }}</td>
                    <td>{{ $app->contact_no }}</td>
                    <td>
                    @if($app->education_level_id==1)
                    {{'SLC'}}

                    @elseif($app->education_level_id==2)
                    {{'10+2'}}

                    @elseif($app->education_level_id==3)
                    {{'Bachelor'}}

                    @elseif($app->education_level_id==4)
                    {{'Master'}}

                    @endif
                    </td>
                    <td>
					@if($app->intrested_course_id==1)
                    {{'Course 1'}}

                    @elseif($app->intrested_course_id==2)
                    {{'Course 2'}}

                    @elseif($app->intrested_course_id==3)
                    {{'Course 3'}}

                    @elseif($app->intrested_course_id==4)
                    {{'Course 4'}}

                    @endif
                    </td>
                    <td>
                    @if($app->intrested_country_id==1)
                    {{'Nepal'}}

                    @elseif($app->intrested_country_id==2)
                    {{'China'}}

                    @elseif($app->intrested_country_id==3)
                    {{'India'}}

                    @elseif($app->intrested_country_id==4)
                    {{'Bhutan'}}

                    @endif

                    </td>


                    <td>
                    	<a type="button" type="button" class="btn btn-success btn-sm"
                           href="{{ route('applications.show', array($app->id)) }}">
                            <i class="flaticon-edit"> View</i>
                        </a>
                         <form action="{{ route('applications.destroy', array($app->id)) }}" method="POST" class="delete-user-form">
                         <input name="_method" value="DELETE" type="hidden">
                                {!! csrf_field() !!}

                                <button type="submit" class="btn btn-sm btn-danger"onclick="return confirm('Are you sure, you want to delete it?');">
                                    <i class="flaticon-delete-button">Delete</i>
                                </button>

                            </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {{ $application->links() }}

@stop