live/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/apply', 'FrontController@applyNow');
Route::post('apply', 'FrontController@storeApplication');
Route::get('/chat', function () {
    return view('chat');
});
// Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout');
    Route::get('logout', 'Auth\LoginController@logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['middleware'=>['auth']],function() {
    Route::get('/home', 'DashboardController@index');
    Route::resource('/home/applications', 'ApplicationController');
    Route::resource('/home/navigation', 'NavigationController');
    Route::resource('/home/advertisement', 'AdvertisementController');

});

live/app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Advertisement extends Model
{
    protected $table='advertisement';
}

live/app/Http/Controllers/AdvertisementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Advertisement;
use Illuminate\Support\Str;
use File;


class AdvertisementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $advertisement_list=Advertisement::orderBy('id','DESC')->paginate(10);
       return view('backend.advertisement.table',compact('advertisement_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('backend.advertisement.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required|unique:advertisement',
            'url' => 'required',
            'image'=>'required',
        ]);
        $advertisement=new Advertisement();
        $advertisement->title=$request->title;
        $advertisement->slug=$slug = Str::slug($advertisement->title, '_');
        /*image upload start*/
        $destination_path = 'uploads/advertisements';
        $name= time() . "-" . $request->file('image')->getClientOriginalName();
        $image = $destination_path . '/' .$name;
        $request->file('image')->move($destination_path, $image);
        /*image upload end*/
        $advertisement->image=$name;
        $advertisement->url=$request->url;
        $advertisement->status=($request->status)?1:0;
            $result=$advertisement->save();
        if($result){
            session()->flash('message', 'Advertisement Saved Succefully.');
            return redirect('home/advertisement');
        }
        else{
            session()->flash('message', 'Something Went Wrong! Please Try Again.');
            return redirect()->back()->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $advertisement=Advertisement::find($id);
        return view('backend.advertisement.edit',compact('advertisement'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' => 'required',
            'url' => 'required',
        ]);
        $advertisement=Advertisement::find($id);
        $advertisement->title=$request->title;
        $advertisement->slug=$slug = Str::slug($advertisement->title, '_');
        /*image upload*/
        if ($request->file('image')!='') {
//                die('here');
            $destination_path = 'uploads/advertisements';
            $name= time() . "-" . $request->file('image')->getClientOriginalName();
            $image = $destination_path . '/' .$name;

            $request->file('image')->move($destination_path, $image);
            $name=$name;
        }
        else{
            $name=$advertisement->image;
        }
        $advertisement->image=$name;
        $advertisement->url=$request->url;
        $advertisement->status=($request->status)?1:0;
        $result=$advertisement->save();
        if($result){
            session()->flash('message', 'Advertisement Updated Succefully.');
            return redirect('home/advertisement');
        }
        else{
            session()->flash('message', 'Something Went Wrong! Please Try Again.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Advertisement::find($id)->delete();
        session()->flash('message', 'Advertisement Deleted Successfully.');
        return redirect('home/advertisement');
    }
}

live/resources/views/backend/advertisement/create.blade.php
@extends('backend.header')
@section('content')
<div class="col-md-12">
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            {{--<ul>--}}
            {{--@foreach ($errors->all() as $error)--}}
            {{--<li>{{ $error }}</li>--}}
            {{--@endforeach--}}
            {{--</ul>--}}
        </div>
    @endif
    {{ Form::open(['url'=>'home/advertisement', 'method'=>'POST', 'class' => 'common-form eq-half-form','enctype'=>'multipart/form-data' ]) }}

        @include('backend.advertisement.partial.form')
        <button type="submit" class="btn btn-info btn-fill">Submit
        </button>
        <div class="clearfix"></div>
    {!! Form::close() !!}
</div>
    @stop

live/resources/views/backend/advertisement/edit.blade.php
@extends('backend.header')
@section('content')
    <div class="col-md-12">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                {{--<ul>--}}
                {{--@foreach ($errors->all() as $error)--}}
                {{--<li>{{ $error }}</li>--}}
                {{--@endforeach--}}
                {{--</ul>--}}
            </div>
        @endif
            {!! Form::model($advertisement, [
                    'route' => ['advertisement.update', $advertisement->id],
                    'class' => 'form-horizontal',
                    'method'=> 'PUT',
                    'enctype'=>'multipart/form-data',
                ])
            !!}
        @include('backend.advertisement.partial.form')
        <button type="submit" class="btn btn-info btn-fill">Update
        </button>
        <div class="clearfix"></div>
        {!! Form::close() !!}
    </div>
@stop

live/resources/views/backend/advertisement/table.blade.php
@extends('backend.header')
@section('content')
    <section class="content-header">
        <h1>
           <span>
        <a href="{{ url('home/advertisement/create') }}">
            <button type="button" class="btn btn-success" id="viewbtn">
                Add New
            </button>
        </a>
    </span>
        </h1>
    </section>
    @if(Session::has('message'))
        <div class="content_top">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ session('message') }}  <!-- equivalent to Session::get('flash_message') -->
            </div>
        </div>
    @endif
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>SN</th>
                <th>Title</th>
                <th>Image</th>
                <th>Url</th>
                <th>Publish</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                <?php
                $i=1;
                ?>
                @foreach($advertisement_list as $advertisement)
                    <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{$advertisement->title}}</td>
                        <td><img src="{{URL::to('/').'/uploads/advertisements/'.$advertisement->image}}" alt="{{$advertisement->image}}" width="50" height="50"></td>
                        <td>{{$advertisement->url}}</td>
                        <td>{{$advertisement->status}}</td>
                        <td>
                            <a type="button" type="button" class="btn btn-primary btn-sm"
                               href="{{ route('advertisement.edit', array($advertisement->id)) }}">
                                <i class="flaticon-edit"> Edit</i>
                            </a>
                            <form action="{{ route('advertisement.destroy', array($advertisement->id)) }}" method="POST" class="delete-user-form">
                                <input name="_method" value="DELETE" type="hidden">
                                {!! csrf_field() !!}

                                <button type="submit" class="btn btn-sm btn-danger"onclick="return confirm('Are you sure, you want to delete it?');">
                                    <i class="flaticon-delete-button">Delete</i>
                                </button>

                            </form>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </div>
    {{ $advertisement_list->links() }}
@stop